model:
  layers:
    - 784
    - 10
  tau_mem: 20.
  tau_stdp: 10.
  alpha_stdp: 1.
  controller_rate: 0.1
  max_val_steps: 100
  max_train_steps: 100
  positive_control: 0.01
  batch_size: 1
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 0.001
    momentum: 0.0
    weight_decay: 1e-5
data:
  batch_size: 1
trainer:
  accelerator: cpu
