model:
  layers:
    - 784
    - 10
  tau_mem: 20.
  tau_stdp: 2.
  alpha_stdp: 1.
  controller_rate: 0.01
  max_val_steps: 100
  max_train_steps: 100
  positive_control: 0.01

optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 0.001
    momentum: 0.1
    weight_decay: 1e-6


data:
  batch_size: 1

trainer:
  max_epochs: 1
  val_check_interval: 5000
