model:
  layers:
    - 784
    - 10
  mode: "spiking"
  tau_mem: 1.
  tau_stdp: 2.54
  controller_rate: 0.1
  controller_precision: 0.01
  target_rates:
    - 0.0
    - 1.0

optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 0.001
    momentum: 0.1
    weight_decay: 1e-6


data:
  batch_size: 1

trainer:
  max_epochs: 1
